/**
 *
 * @author Akmal N.F
 */
public class Exception12 extends Exception {
    private String Teks;

    Exception12(String s) {
        Teks = "Exception generated by: " + s;
        System.out.println(Teks);
    }
}

class Eksepsi {
    static void tampil(String s) throws Exception {
        System.out.println("Tampil");
        if (s.equals("amir")) {
            throw new Exception12(s);
        }
        System.out.println("OK!");
    }

    public static void main(String[] args) throws Exception {
        try {
            tampil("ali");
            tampil("amir");
        } catch (Exception12 ex) {
            System.out.println("Tangkap:" + ex);
        }
    }
}
